### PR TITLE
Add GLSLViewer java app , glsl example fragments files & texture files

### PR DESCRIPTION
**Pull request by jsosai**
the js.glsl.GLSLViewer.java app to test some fragment shaders & texture
files, Note.  supplied jars for LWJGL 3 (3.2.0) jar files are for
windows platform other platforms can be downloaded from https://www.lwjgl.org/customize,
 also need:
 pngdecoder-1.0.jar for png files for  textures 
 joml-1.9.12.jar OpenGL Math library.

### CODE REVIEW

**Comment by thargor6** [comment]
cool! Should be integrated as completely new window then. I can do it, but will take some time, as I'm covered with other projects now.

**Comment by thargor6** [comment]
No, but I'm using IntelliJ and Java 10, maybe this makes the difference

**Comment by thargor6** [comment]
It is not really integrated yet, so you can comment it out

**Comment by sidwellr** [comment]
That's what I ended up doing. Thanks.

**Pull request merged**
