### PR TITLE
pull requests 3-15-17

### PR DESCRIPTION
**Pull request by snicker02**

### CODE REVIEW

**Comment by snicker02** [comment]
If I did not do this correctly please let me know.... My first time

**Comment by thargor6** [comment]
Confirmed it!

Cheers!

2017-03-16 2:02 GMT+01:00 snicker02 <notifications@github.com>:

**Comment by snicker02** [comment]
I accidentally added 2 TileHlp.java please remove this one.... it is wrong. https://github.com/thargor6/JWildfire/blob/master/src/org/jwildfire/create/tina/variation/TileHlp.java

**Comment by thargor6** [comment]
Done!

2017-03-16 23:20 GMT+01:00 snicker02 <notifications@github.com>:

**Pull request merged**
