### PR TITLE
Option to mirror affine translations

### PR DESCRIPTION
**Pull request by GreggHelt2**
Andreas, can you look at this when you have a chance? It modifies some of the UI code, and I think it works fairly well but there are large parts of JWildfire that I'm not familiar with so there may be ripple effects I'm not aware of! This pull adds a "Mirror Translation" toggle-button to the Affine tab (see attached images). The toggle applies to all three planes XY, YZ, and ZX. When toggled on, if viewing pre-affine, changing translation (01 or 02 coefficients) is mirrored by reversing the translation (setting post-affine to -01 and -02). And vice-versa if viewing post-affine. This mirroring is very handy for some of the new variations I've added such as Inversion and KleinGroup and for existing variations such as Spherical, which use mathematical operations that typically in other contexts are composed with a translation T and its inverse T' to move their center from the origin:  G_shifted = T(G(T')). A boolean is added to the transform in the flame so that the mirror toggle state is saved to and restored from flame files. What do you think?

mirrortranslation_pre
mirrortranslation_post

### CODE REVIEW

**Comment by thargor6** [comment]
Interesting feature! I do not see problems so far, will test it! Thanks for all your work!

Cheers!

**Comment by sidwellr** [comment]
I found one issue with this: since the steps for post-affine transforms are
done in the same order as the steps for pre-affine transforms, merely
reversing the translations won't exactly mirror them unless there are no
rotations or scaling. For example, create a new flame and add a transform
with starblur. Then add a final with linear3D. Enable Mirror Translations
on the final. Moving the final triangle by itself will have no effect due
to the Mirror Translations. But now rotate or scale the final Post TF. Now
moving the final triangle will move the star.

I'm not sure what the best way to address this. Reversing the order when
Mirror Translations is enabled would solve this issue, but result in an
unexpected change in the flame if Mirror Translations is disabled. I
personally would like to see the whole affine transforms mirrored, not just
the translations. If that is done, the affine coefficients could be changed
to effect a true mirror without changing the order. For example, if the
pre-affine coefficients are X1=Y2=2, X2=Y1=0, O1=O2=1, the post-affine
coefficients to mirror it are X1=Y2=0.5, X2=Y1=0, O1=O2=-0.5. This would
work, but the values might be confusing to users.

A different idea I had (but haven't had a chance to persue) is to implement
"prepost" variations, that would be executed both before and after the
normal ones. Pre would have the normal effect, and post would have the
inverse effect. A varation prepost_affine would work much like I just
described (though I'd probably parameterize it in terms of scaling,
rotation, and translation instead of affine coefficients). A variation
prepost_mobius is one I'd really like to try (I have no idea whether it
would really be useful, though I think it could be). I don't know what
others would be useful. But just an idea I'm tossing out to see what
everyone else thinks.

Rick Sidwell

**Comment by GreggHelt2** [comment]
Thanks for the comments!
I want to keep this conversation going, but think we should move it over to the forum. If either of you (thargor6 and sidwellr) don't want this cross-posted to the forum, please let me know soon, otherwise I'll repost in the forum's "Request new features" section.

**Comment by sidwellr** [comment]
That's a good idea. Please do it.

**Comment by thargor6** [comment]
As I'm planning a new release next week we could mark it as "experimental", and optimize it later

**Comment by snicker02** [comment]
Gregg I think it would be helpful if we had some sample flames to see how exactly they work with your new variations and others.

**Pull request merged**
